/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2e3131",
        "tertiary-container": "#2b3a31",
        "on-background": "#191c1c",
        "on-surface-variant": "#434843",
        "on-primary-container": "#92a597",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#bacbbe",
        "surface-container-lowest": "#ffffff",
        background: "#f9f9f8",
        "on-primary-fixed-variant": "#3a4b3f",
        surface: "#f9f9f8",
        "tertiary-fixed": "#d5e7d9",
        "inverse-primary": "#b8cbbc",
        "on-secondary-fixed-variant": "#474746",
        "surface-dim": "#d9dad9",
        "primary-fixed-dim": "#b8cbbc",
        "primary-fixed": "#d4e7d8",
        "surface-container-low": "#f3f4f3",
        "primary-container": "#2a3b30",
        tertiary: "#16241c",
        "secondary-container": "#e2dfde",
        "surface-container-high": "#e7e8e7",
        "on-tertiary-fixed-variant": "#3b4a40",
        "surface-container": "#edeeed",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e1e3e2",
        "on-tertiary-fixed": "#101f16",
        outline: "#737872",
        "surface-bright": "#f9f9f8",
        "on-tertiary-container": "#93a498",
        "surface-tint": "#516256",
        error: "#ba1a1a",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#c8c6c5",
        "on-surface": "#191c1c",
        secondary: "#5f5e5e",
        "surface-variant": "#e1e3e2",
        "on-primary-fixed": "#0f1f15",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-container": "#636262",
        primary: "#15251b",
        "outline-variant": "#c3c8c1",
        "inverse-on-surface": "#f0f1f0",
        "secondary-fixed": "#e5e2e1",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};
